resources:
  repositories:
  - repository: RemoteBlazorWebView  # The name used to reference this repository in the checkout step
    type: github
    endpoint: RemoteBlazorWebView
    name: budcribar.RemoteBlazorWebView

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
- checkout: RemoteBlazorWebView

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'NuGet push packages'
  inputs:
    command: push
    publishVstsFeed: 'RemoteBlazorWebView/Nugets2'
    allowPackageConflicts: false
    packagesToPush: 'artifacts/*.nupkg'
 
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'artifacts'
    ArtifactName: 'dropNugets'
    publishLocation: 'Container'
    