<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<RootNamespace>WpfBlazor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Wpf" Version="8.0.93" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="8.0.11" />
  </ItemGroup>

</Project>
